language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 myproject"
  - pyflakes -x W myproject

script:
  - py.test
